name: Build ESP32-S3 Custom

on:
  workflow_dispatch:

jobs:
  build_s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install ESP-IDF and Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: 'v5.1.2'
        target: 'esp32s3'
        # On force ESP-IDF à chercher le projet là où se trouve le vrai CMakeLists.txt de l'application
        path: '.' 

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: My-ESP32S3-Firmware
        path: |
          build/retro-go.img
          build/merged-firmware.bin
          build/**/*.bin
