name: ci2

on:
  workflow_dispatch:      # Permet de lancer le build manuellement avec le bouton
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup runner
      run: |
        sudo rm -rf /opt/microsoft /usr/local/.ghcup /usr/share/dotnet /usr/share/swift /usr/lib/llvm*

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Étape 1 : On construit l'image Docker de base (qui contient ESP-IDF)
    - name: Build Docker Image
      run: |
        docker build -t retro-go-builder .

    # Étape 2 : On force Docker à lancer la configuration et la compilation SPECIFIQUE au S3
    # On lui demande ensuite de jeter le résultat dans notre dossier local /build
    - name: Compile and Extract ESP32-S3
      run: |
        mkdir -p build
        docker run --rm -v $(pwd)/build:/dist retro-go-builder sh -c "
          python rg_tool.py mconfig esp32-s3-devkit && \
          idf.py build && \
          cp build/retro-go.img /dist/ 2>/dev/null || cp build/merged-firmware.bin /dist/ 2>/dev/null || cp build/**/*.bin /dist/
        "

    # Étape 3 : On récupère le précieux fichier .img
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: My-ESP32S3-Firmware
        path: build/
